//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: messages_RFC_ssl_wrapper.proto
// Note: requires additional types generated from: messages_RFC_ssl_detection.proto
// Note: requires additional types generated from: messages_RFC_ssl_geometry.proto
namespace RFC.SSLVisionLib
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SSL_WrapperPacket")]
	public partial class SSL_WrapperPacket : global::ProtoBuf.IExtensible
	{
		public SSL_WrapperPacket() {}


		private SSL_DetectionFrame _detection = null;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"detection", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public SSL_DetectionFrame detection
		{
			get { return _detection; }
			set { _detection = value; }
		}

		private SSL_GeometryData _geometry = null;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"geometry", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public SSL_GeometryData geometry
		{
			get { return _geometry; }
			set { _geometry = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

}